name: adinkra_icons
description: Adinkra Icons pack in your Flutter App.
version: 0.0.1
homepage: https://github.com/4eug/adinkra-icons-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  path: ^1.8.1

dev_dependencies:
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  recase: ^4.0.0

flutter:
  assets:
    - assets/
